# Database Configuration
#spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/jewelry_management?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.url=${DB_URL:jdbc:mariadb://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/sys?user=4F7Qv8wLbj7UoWf.root&password=Zx5CziHBiugpjMAN&sslMode=verify-full}
#spring.datasource.username=${DB_USERNAME:root}
#spring.datasource.password=${DB_PASSWORD:Ronal@2626}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.example=INFO

# Server
server.port=${PORT:8081}

# Optimization for Free Tiers
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=30000
